<a href="https://colab.research.google.com/github/Shashank18ram/Data-Science/blob/main/DecisionTrees_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import google.colab
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/sales.csv')
df.head()

,Unnamed: 0,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,high
0,1,138,73,11,276,120,Bad,42,17,Yes,Yes,yes
1,2,111,48,16,260,83,Good,65,10,Yes,Yes,yes
2,3,113,35,10,269,80,Medium,59,12,Yes,Yes,yes
3,4,117,100,4,466,97,Medium,55,14,Yes,Yes,no
4,5,141,64,3,340,128,Bad,38,13,Yes,No,no

In [ ]:
df_sales = df.copy()

In [ ]:
#Encode the Nominal columns
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)
#df_sales['US'] = ohe.fit_transform(df_sales[['US']]).toarray()
ohe_1_urban = ohe.fit_transform(df_sales[['Urban']])
ohe1_df = pd.DataFrame(ohe_1_urban, columns=['Urban_Cat'])
ohe_2_us = ohe.fit_transform(df_sales[['US']])
ohe_2_df = pd.DataFrame(ohe_2_us, columns=['US_Cat'])

In [ ]:
df_sales_new = pd.concat([df_sales, ohe1_df,ohe_2_df],axis=1)
df_sales_new.head()

,Unnamed: 0,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,high,Urban_Cat,US_Cat
0,1,138,73,11,276,120,Bad,42,17,Yes,Yes,yes,1.0,1.0
1,2,111,48,16,260,83,Good,65,10,Yes,Yes,yes,1.0,1.0
2,3,113,35,10,269,80,Medium,59,12,Yes,Yes,yes,1.0,1.0
3,4,117,100,4,466,97,Medium,55,14,Yes,Yes,no,1.0,1.0
4,5,141,64,3,340,128,Bad,38,13,Yes,No,no,1.0,0.0

In [ ]:
#Drop all text columns from df_sales_new
df_sales_new.drop(columns = ['Unnamed: 0','Urban','US'],inplace=True)

In [ ]:
df_sales_new.head()

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,high,Urban_Cat,US_Cat
0,138,73,11,276,120,Bad,42,17,yes,1.0,1.0
1,111,48,16,260,83,Good,65,10,yes,1.0,1.0
2,113,35,10,269,80,Medium,59,12,yes,1.0,1.0
3,117,100,4,466,97,Medium,55,14,no,1.0,1.0
4,141,64,3,340,128,Bad,38,13,no,1.0,0.0

In [ ]:
#label Encode the high column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_sales_new['ShelveLoc'] = le.fit_transform(df_sales_new['ShelveLoc'])
df_sales_new['high'] = le.fit_transform(df_sales_new['high'])
df_sales_new.head()

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,high,Urban_Cat,US_Cat
0,138,73,11,276,120,0,42,17,1,1.0,1.0
1,111,48,16,260,83,1,65,10,1,1.0,1.0
2,113,35,10,269,80,2,59,12,1,1.0,1.0
3,117,100,4,466,97,2,55,14,0,1.0,1.0
4,141,64,3,340,128,0,38,13,0,1.0,0.0

In [ ]:
#label encode 'high' column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#df_sales_new['ShelveLoc'] = le.fit_transform(df_sales_new['ShelveLoc'])
df_sales_new['high'] = le.fit_transform(df_sales_new['high'])
df_sales_new.head()

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,high,Urban_Cat,US_Cat
0,138,73,11,276,120,0,42,17,1,1.0,1.0
1,111,48,16,260,83,1,65,10,1,1.0,1.0
2,113,35,10,269,80,2,59,12,1,1.0,1.0
3,117,100,4,466,97,2,55,14,0,1.0,1.0
4,141,64,3,340,128,0,38,13,0,1.0,0.0

In [ ]:
#Step1; generate X and Y Dataset
X = df_sales_new.drop(columns=['high'],axis=1)
y = df_sales_new['high']
#

In [ ]:
X.head()

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban_Cat,US_Cat
0,138,73,11,276,120,0,42,17,1.0,1.0
1,111,48,16,260,83,1,65,10,1.0,1.0
2,113,35,10,269,80,2,59,12,1.0,1.0
3,117,100,4,466,97,2,55,14,1.0,1.0
4,141,64,3,340,128,0,38,13,1.0,0.0

In [ ]:
y.head()

0    1
1    1
2    1
3    0
4    0
Name: high, dtype: int64